# Generated by Django 5.2 on 2025-09-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("timb_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_grade_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("encrypted_composition", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timb_dashboard.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("client_name", models.CharField(max_length=200)),
                ("encrypted_client_details", models.TextField()),
                (
                    "requested_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "filled_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delivery_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PARTIALLY_FILLED", "Partially Filled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("encrypted_special_requirements", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timb_dashboard.merchant",
                    ),
                ),
                (
                    "custom_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant_app.customgrade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AggregationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.CharField(max_length=100)),
                ("encrypted_rule_logic", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timb_dashboard.merchant",
                    ),
                ),
                (
                    "target_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant_app.customgrade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomGradeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "minimum_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "base_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timb_dashboard.tobaccograde",
                    ),
                ),
                (
                    "custom_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="merchant_app.customgrade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommended_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "recommended_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("confidence_score", models.FloatField()),
                ("reasoning", models.TextField()),
                ("encrypted_ai_analysis", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_acted_upon", models.BooleanField(default=False)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timb_dashboard.tobaccograde",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timb_dashboard.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market Risk"),
                            ("PRICE", "Price Risk"),
                            ("SUPPLY", "Supply Risk"),
                            ("DEMAND", "Demand Risk"),
                            ("FARMER", "Farmer Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("risk_score", models.FloatField()),
                ("description", models.TextField()),
                ("encrypted_mitigation_strategies", models.TextField()),
                ("assessment_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timb_dashboard.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MerchantInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("average_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("location", models.CharField(max_length=200)),
                ("encrypted_storage_details", models.TextField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timb_dashboard.tobaccograde",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timb_dashboard.merchant",
                    ),
                ),
            ],
            options={
                "unique_together": {("merchant", "grade", "location")},
            },
        ),
    ]
