# Generated by Django 4.2.7 on 2025-10-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant_app", "0002_aggregations"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aggregatedgrade",
            new_name="merchant_ap_merchan_11c4ae_idx",
            old_name="aggregated_merchant_computed",
        ),
        migrations.RenameIndex(
            model_name="aggregatedgrade",
            new_name="merchant_ap_rule_se_deee4b_idx",
            old_name="aggregated_ruleset_computed",
        ),
        migrations.RenameIndex(
            model_name="aggregationruleset",
            new_name="merchant_ap_merchan_65242e_idx",
            old_name="merchant_rulertype_created",
        ),
    ]
