# Generated by Django 4.2.7 on 2025-10-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0003_rename_aggregated_merchant_computed_merchant_ap_merchan_11c4ae_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgrade',
            name='acquired_weight_per_grade',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Acquired weight per grade in kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='customgrade',
            name='required_weight_per_grade',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Required weight per grade in kg', max_digits=10),
        ),
    ]
