# Generated by Django 5.2 on 2025-09-24 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="encrypted_data",
            new_name="encrypted_sensitive_data",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Contact phone number",
                max_length=15,
                null=True,
                verbose_name="Phone Number",
            ),
        ),
        migrations.CreateModel(
            name="EncryptedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_ref",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("encrypted_content", models.TextField()),
                ("data_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Encrypted Data",
                "verbose_name_plural": "Encrypted Data",
                "db_table": "tobacco_encrypted_data",
                "indexes": [
                    models.Index(
                        fields=["data_ref"], name="tobacco_enc_data_re_17d7d0_idx"
                    ),
                    models.Index(
                        fields=["data_type"], name="tobacco_enc_data_ty_2d245c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Login Attempt",
                "verbose_name_plural": "Login Attempts",
                "db_table": "tobacco_login_attempts",
                "indexes": [
                    models.Index(
                        fields=["username", "timestamp"],
                        name="tobacco_log_usernam_095b30_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="tobacco_log_ip_addr_7af606_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "tobacco_user_sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="tobacco_use_user_id_f2719e_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="tobacco_use_session_a7b67c_idx"
                    ),
                ],
            },
        ),
    ]
