# Generated by Django 5.2 on 2025-09-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FraudDetectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_version", models.CharField(max_length=20)),
                ("encrypted_model_parameters", models.TextField()),
                ("training_accuracy", models.FloatField()),
                ("validation_accuracy", models.FloatField()),
                ("false_positive_rate", models.FloatField()),
                ("false_negative_rate", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ModelPerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("metric_name", models.CharField(max_length=50)),
                ("metric_value", models.FloatField()),
                ("measurement_date", models.DateTimeField(auto_now_add=True)),
                ("encrypted_metadata", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PredictionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("YIELD", "Yield Prediction"),
                            ("FRAUD", "Fraud Detection"),
                            ("PRICE", "Price Prediction"),
                            ("DEMAND", "Demand Prediction"),
                            ("RISK", "Risk Assessment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_used", models.CharField(max_length=100)),
                ("input_data", models.JSONField()),
                ("prediction_result", models.JSONField()),
                ("confidence_score", models.FloatField()),
                ("encrypted_detailed_analysis", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="YieldPredictionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("rainfall_mm", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "temperature_avg",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("number_of_farmers", models.IntegerField()),
                (
                    "total_hectarage",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "predicted_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "actual_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("economic_factors", models.JSONField(default=dict)),
                ("encrypted_additional_data", models.TextField(blank=True)),
                ("prediction_accuracy", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
