# Generated by Django 4.2.7 on 2025-10-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timb_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobaccofloor',
            name='market_open',
            field=models.BooleanField(default=False, help_text='Whether trading is open on this floor'),
        ),
    ]
