# Generated by Django 5.2.7 on 2025-10-16 21:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timb_dashboard', '0002_tobaccofloor_market_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('AI_DETECTION', 'AI Detection'), ('MANUAL_REVIEW', 'Manual Review'), ('PATTERN_ANALYSIS', 'Pattern Analysis'), ('THRESHOLD_BREACH', 'Threshold Breach')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timb_dashboard.transaction')),
            ],
            options={
                'db_table': 'timb_fraud_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', '-created_at'], name='timb_fraud__alert_t_bcdcd7_idx'), models.Index(fields=['severity', 'is_resolved'], name='timb_fraud__severit_c44fbc_idx'), models.Index(fields=['transaction', '-created_at'], name='timb_fraud__transac_54e8a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='YieldPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('ANNUAL', 'Annual'), ('SEASONAL', 'Seasonal'), ('REGIONAL', 'Regional'), ('FARM_LEVEL', 'Farm Level')], max_length=20)),
                ('year', models.IntegerField()),
                ('region', models.CharField(blank=True, max_length=100)),
                ('rainfall_mm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temperature_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_of_farmers', models.IntegerField()),
                ('total_hectarage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inflation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('predicted_yield_kg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('confidence_level', models.DecimalField(decimal_places=3, max_digits=5)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=15)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=15)),
                ('model_version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timb_yield_predictions',
                'ordering': ['-year', '-created_at'],
                'indexes': [models.Index(fields=['year', 'region'], name='timb_yield__year_233138_idx'), models.Index(fields=['prediction_type', '-created_at'], name='timb_yield__predict_226113_idx')],
            },
        ),
    ]
