# Generated by Django 4.2.7 on 2025-10-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livetransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Live Transaction', 'verbose_name_plural': 'Live Transactions'},
        ),
        migrations.AddIndex(
            model_name='realtimeprice',
            index=models.Index(fields=['grade', 'floor'], name='realtime_da_grade_i_2e2d87_idx'),
        ),
        migrations.AddIndex(
            model_name='realtimeprice',
            index=models.Index(fields=['-last_updated'], name='realtime_da_last_up_34644d_idx'),
        ),
    ]
